### ISSUE TITLE
separate dev and prod environments

### ISSUE THREAD

**Issue by izi01** [Helfer-Portal/helponspot-lambdas#41]
Find a way to create a stable prod environment. 

Goal: 
- additional stage in API gateway 
- dedicated lambda functions for prod
- unified deployment of all prod lambdas 
- preferably one click deployments

**Comment by meteohr** [comment]
Also consider:

- Additional production database
- Better user management for prod database (use dedicated user/arn with restricted permissions for lambdas)

**Comment by izi01** [comment]
created a stage variable in API gateway. Variable is part of every of every lambda connection. 
So two lambdas need to exist for every endpoint. Like:  HoS_post-user_dev  and HoS_post-user_prod

deploy.sh script will have the option to select which stage to deploy to.
So this script should also be able to create new lambdas and set them up correctly
